config/routes.rb
require 'api_constraints'

Jupiter::Application.routes.draw do 

  resources :attachments

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1) do
        resources :shareables, path: '/shareable', only: [:create] 
        devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
        resources :messages, only: [:create, :index, :show] 
    end
    
    post '/mogreet/callback', to: 'callback#mogreet_callback', :defaults => { :format => 'xml' }
    post '/mogreet/response', to: 'callback#handle_mogreet_response'
    post '/twilio/callback', to: 'callback#twilio_callback'
    
    resources :recordings do
      collection do 
        get 'handle' => 'recordings#handle'
      end
      collection do 
        get 'complete' => 'recordings#complete'
      end
    end
  end
  
  scope '/a' do
    
    resources :help_docs
    
    resources :community_feeds, only: [:index] 

    resources :emails

    resources :messages
    
    resources :recordings

    resources :sms_archives

    resources :client_numbers

    resources :users_clients

    resources :recipients

    resources :sms_responses

    devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
    
    resources :shareables

    resources :clients

    resources :clicks do
      collection do 
        get '/' => 'clicks#create'
      end
    end
  
    post '/clicks/default/:id', to:  "clicks#default"
    
    get '/contact_us', to:  "home#contact_us"

    resources :email_templates
  
    resources :user_profiles
  end
  
  namespace :admin do |admin|
    resources :user_profiles
    resources :clients
    resources :messages
    resources :users
    resources :sms_responses
  end

  get '*short' => 'api/clicks#create', short: /\w{6}/

  root :to => "home#index"
  
  

end

app/models/client_number.rb
class ClientNumber < ActiveRecord::Base
  include FormatterModule
  attr_accessible :client_id, :phone
  validates :phone, :uniqueness => true, :presence => true
  belongs_to :client, :dependent => :destroy
  
  
  def self.get_number(cid)
    ClientNumber.where(:client_id => cid).order('random()').first.phone
  end
end

app/controllers/client_numbers_controller.rb
class ClientNumbersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /client_numbers
  # GET /client_numbers.json
  def index
  
    @links_grid = initialize_grid(ClientNumber)
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @client_numbers }
    end
  end

  # GET /client_numbers/1
  # GET /client_numbers/1.json
  def show
    @client_number = ClientNumber.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client_number }
    end
  end

  # GET /client_numbers/new
  # GET /client_numbers/new.json
  def new
    @client_number = ClientNumber.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client_number }
    end
  end

  # GET /client_numbers/1/edit
  def edit
    @client_number = ClientNumber.find(params[:id])
  end

  # POST /client_numbers
  # POST /client_numbers.json
  def create
    @client_number = ClientNumber.new(params[:client_number])

    respond_to do |format|
      if @client_number.save
        format.html { redirect_to @client_number, notice: 'Client number was successfully created.' }
        format.json { render json: @client_number, status: :created, location: @client_number }
      else
        format.html { render action: "new" }
        format.json { render json: @client_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /client_numbers/1
  # PUT /client_numbers/1.json
  def update
    @client_number = ClientNumber.find(params[:id])

    respond_to do |format|
      if @client_number.update_attributes(params[:client_number])
        format.html { redirect_to @client_number, notice: 'Client number was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_numbers/1
  # DELETE /client_numbers/1.json
  def destroy
    @client_number = ClientNumber.find(params[:id])
    @client_number.destroy

    respond_to do |format|
      format.html { redirect_to client_numbers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/client_numbers_helper.rb
module ClientNumbersHelper
end

app/views/client_numbers/_form.html.erb
<%= form_for(@client_number) do |f| %>
  <% if @client_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client_number.errors.count, "error") %> prohibited this client_number from being saved:</h2>

      <ul>
      <% @client_number.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><%= f.label 'Application' %><br />
  <%= f.select( :client_id, Client.all.collect {|a| [a.title, a.id]} ) %></div>
   
 
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/client_numbers/edit.html.erb
<h1>Editing client_number</h1>

<%= render 'form' %>

<%= link_to 'Show', @client_number %> |
<%= link_to 'Back', client_numbers_path %>

app/views/client_numbers/index.html.erb
<h1>Client Numbers</h1>

<%= link_to 'New Client number', new_client_number_path, class: "btn" %>

<%= grid(@links_grid)  do |g|

	g.column :name => 'Id', :attribute => 'id' do |client_number|
  	  client_number.id
	end

	g.column :name => 'Client Id', :attribute => 'client_id' do |client_number|
		client_number.client_id
	end
  
	g.column :name => 'Phone', :attribute => 'phone'  do |client_number|
		client_number.phone
	end
			  
	g.column :name => 'Created', :attribute => 'created_at', filter: false do |client_number|
		client_number.formatted_created_at
	end
			  
	g.column :name => 'Updated', :attribute => 'updated_at', filter: false do |client_number|
		client_number.formatted_updated_at
	end
	
	g.column do |client_number|
	    link_to('Edit', edit_client_number_path(client_number))
	end
	g.column do |client_number|
		link_to('Delete', client_number_path(client_number), :confirm => "Are you sure?", :method => :delete)
	end

end -%>

app/views/client_numbers/new.html.erb
<h1>New client_number</h1>

<%= render 'form' %>

<%= link_to 'Back', client_numbers_path %>

app/views/client_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Client:</b>
  <%= @client_number.client_id %>
</p>

<p>
  <b>Phone:</b>
  <%= @client_number.phone %>
</p>


<%= link_to 'Edit', edit_client_number_path(@client_number) %> |
<%= link_to 'Back', client_numbers_path %>