config/routes.rb
require 'api_constraints'

Jupiter::Application.routes.draw do 

  resources :attachments

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1) do
        resources :shareables, path: '/shareable', only: [:create] 
        devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
        resources :messages, only: [:create, :index, :show] 
    end
    
    post '/mogreet/callback', to: 'callback#mogreet_callback', :defaults => { :format => 'xml' }
    post '/mogreet/response', to: 'callback#handle_mogreet_response'
    post '/twilio/callback', to: 'callback#twilio_callback'
    
    resources :recordings do
      collection do 
        get 'handle' => 'recordings#handle'
      end
      collection do 
        get 'complete' => 'recordings#complete'
      end
    end
  end
  
  scope '/a' do
    
    resources :help_docs
    
    resources :community_feeds, only: [:index] 

    resources :emails

    resources :messages
    
    resources :recordings

    resources :sms_archives

    resources :client_numbers

    resources :users_clients

    resources :recipients

    resources :sms_responses

    devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
    
    resources :shareables

    resources :clients

    resources :clicks do
      collection do 
        get '/' => 'clicks#create'
      end
    end
  
    post '/clicks/default/:id', to:  "clicks#default"
    
    get '/contact_us', to:  "home#contact_us"

    resources :email_templates
  
    resources :user_profiles
  end
  
  namespace :admin do |admin|
    resources :user_profiles
    resources :clients
    resources :messages
    resources :users
    resources :sms_responses
  end

  get '*short' => 'api/clicks#create', short: /\w{6}/

  root :to => "home#index"
  
  

end

app/models/recording.rb
class Recording < ActiveRecord::Base
   include FormatterModule
  attr_accessible :tag, :url, :client_id, :user_id
  validates_presence_of :url, :client_id, :user_id
end

app/controllers/api/recordings_controller.rb
require 'twilio-ruby'

module Api
    class RecordingsController < ApplicationController
       skip_authorization_check
   
       respond_to :xml, :text 
 
      def handle
        @response = Twilio::TwiML::Response.new do |r|
          r.Say 'Please record your message after the tone. Go Stella Dot!'
          r.Record :maxLength => '600', :action => '/api/recordings/complete', :method => 'get'
          r.Say 'Roger and out.'
        end

        render :text => @response.text, :type => :builder, :layout => false
    
      end
  
      def complete
    
        @recording = Recording.new(:tag => "A test message", :url => params["RecordingUrl"], :user_id => 1, :client_id => 1)
        @recording.save
    
      end
  
  
    end
end

app/controllers/recordings_controller.rb
require 'twilio-ruby'

class RecordingsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  respond_to :html
  
  def new

    account_sid = ENV["TWILIO_SID"]
    auth_token = ENV["TWILIO_TOKEN"]
    app_sid = ENV["TWILIO_APP_SID"]

     capability = Twilio::Util::Capability.new account_sid, auth_token
     capability.allow_client_outgoing app_sid
     token = capability.generate

     render partial: "record", locals: { :token => token} 
  end
  
  # GET /recordings
  # GET /recordings.json
  def index
    @user = User.find(current_user.id)
    
    @links_grid = initialize_grid(Recording.where(:client_id => @user.client_id))

    respond_to do |format|
      format.html # index.html.erb
    end
    
  end

  # GET /recordings/1
  # GET /recordings/1.json
  def show
    @recording = Recording.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  

  # GET /recordings/1/edit
  def edit
    @recording = Recording.find(params[:id])
  end

  def create
    @recording = Recording.new(params[:recording])

    respond_to do |format|
      if @recording.save
        format.html { redirect_to @recording, notice: 'Recording was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /recordings/1
  # PUT /recordings/1.json
  def update
    @recording = Recording.find(params[:id])

    respond_to do |format|
      if @recording.update_attributes(params[:recording])
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /recordings/1
  # DELETE /recordings/1.json
  def destroy
    @recording = Recording.find(params[:id])
    @recording.destroy

    respond_to do |format|
      format.html { redirect_to recordings_url }
    end
  end
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/views/recordings/_form.html.erb
<%= form_for(@recording) do |f| %>
  <% if @recording.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recording.errors.count, "error") %> prohibited this recording from being saved:</h2>

      <ul>
      <% @recording.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recordings/_record.html.erb
		<!-- @start snippet -->
		<script type="text/javascript" src="//static.twilio.com/libs/twiliojs/1.1/twilio.min.js"></script>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
		<script type="text/javascript">
 
		var connection=null;
		$(document).ready(function(){
		    Twilio.Device.setup("<%= token %>", {debug: true});
 
			
			$("#call").click(function() {  
				Twilio.Device.connect();
			});
			$("#hangup").click(function() {  
  				connection.sendDigits("#");
			});

			Twilio.Device.ready(function (device) {
				$('#status').text('Ready to start recording');
			});

			Twilio.Device.offline(function (device) {
				$('#status').text('Offline');
			});

			Twilio.Device.error(function (error) {
				$('#status').text(error);
			});

			Twilio.Device.connect(function (conn) {
				connection=conn;
				$('#status').text("On Air");
				$('#status').css('color', 'red');
				toggleCallStatus();
			});

			Twilio.Device.disconnect(function (conn) {
				$('#status').html('Recording ended<br/><a href="/recordings">view recording list</a>');
				$('#status').css('color', 'black');
				toggleCallStatus();
			});
			
			function toggleCallStatus(){
				$('#call').toggle();
				$('#hangup').toggle();
			}
		});
		   
			
		</script>
		<!-- @end snippet -->


		<div align="center">
		<!-- @start snippet -->
			<h3>Create a Recording</h3>
			<input type="button" id="call" value="Begin Recording"/>
			<input type="button" id="hangup" value="Stop Recording" style="display:none;"/>
			<div id="status">
				Offline
			</div>
		<!-- @end snippet -->
		</div>

app/views/recordings/edit.html.erb
<h1>Editing recording</h1>

<%= render 'form' %>

<%= link_to 'Show', @recording %> |
<%= link_to 'Back', recordings_path %>

app/views/recordings/index.html.erb
<%- model_class = Recording -%>
<h1>All recordings</h1>

<%= link_to 'New Recording', new_recording_path %>

<%= grid(@links_grid, :show_filters => :always)  do |g|

	g.column :name => 'Id', :attribute => 'id' do |recording|
  		recording.id
	end

	g.column :name => 'Tag', :attribute => 'tag' do |recording|
		recording.tag
	end
  
	g.column :name => 'Recording', :attribute => 'url'  do |recording|
		link_to('Listen to Recording', recording.url)
	end

	g.column :name => 'Created by', :attribute => 'user_id' do |recording|
		recording.user_id
	end
			  
	g.column :name => 'Created', :attribute => 'created_at', filter: false do |recording|
		recording.formatted_created_at
	end
			  
	g.column :name => 'Updated', :attribute => 'updated_at', filter: false do |recording|
		recording.formatted_updated_at
	end
			  

end -%>

app/views/recordings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_recording_path(@recording) %> |
<%= link_to 'Back', recordings_path %>