config/routes.rb
require 'api_constraints'

Jupiter::Application.routes.draw do 

  resources :attachments

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1) do
        resources :shareables, path: '/shareable', only: [:create] 
        devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
        resources :messages, only: [:create, :index, :show] 
    end
    
    post '/mogreet/callback', to: 'callback#mogreet_callback', :defaults => { :format => 'xml' }
    post '/mogreet/response', to: 'callback#handle_mogreet_response'
    post '/twilio/callback', to: 'callback#twilio_callback'
    
    resources :recordings do
      collection do 
        get 'handle' => 'recordings#handle'
      end
      collection do 
        get 'complete' => 'recordings#complete'
      end
    end
  end
  
  scope '/a' do
    
    resources :help_docs
    
    resources :community_feeds, only: [:index] 

    resources :emails

    resources :messages
    
    resources :recordings

    resources :sms_archives

    resources :client_numbers

    resources :users_clients

    resources :recipients

    resources :sms_responses

    devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
    
    resources :shareables

    resources :clients

    resources :clicks do
      collection do 
        get '/' => 'clicks#create'
      end
    end
  
    post '/clicks/default/:id', to:  "clicks#default"
    
    get '/contact_us', to:  "home#contact_us"

    resources :email_templates
  
    resources :user_profiles
  end
  
  namespace :admin do |admin|
    resources :user_profiles
    resources :clients
    resources :messages
    resources :users
    resources :sms_responses
  end

  get '*short' => 'api/clicks#create', short: /\w{6}/

  root :to => "home#index"
  
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check
  
  respond_to :html 
  
  def index
    render action: "index", layout: "home-page"
  end
  
  def contact_us
    render action: "contact", layout: "home-page"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_usernav.html.erb
<div id="containerNav">
	<div class="navbar">
	
	<div class="navbar-inner">
	  <a class="brand" href="//www.inv.to">
	    Inviter
	  </a>
	  <ul class="nav">
	
	<% if user_signed_in? %>
	<li><a href="<%= messages_path %>">SMS</a></li>
	<li><a href="<%= community_feeds_path %>">Community</a></li>
	<li><a href="<%= user_profiles_path %>">Account</a></li>
	<li><a href="/a/users/logout" data-method="delete">Logout</a></li>

	<% else %>
	<li><%= link_to "Log In", new_user_session_url(:protocol => "https")  %></li>
	 
	<% end %>
	 </ul>
 </div>
	
  </div>
</div>

app/views/home/contact.html.erb
<div>
	Email: admin@inv.to
</div>

app/views/home/index.html.erb
<div id="main" class="signed-out-info signed-out-homepage logged-out">
	
<div id="ext_container">

<div id="container" class="homecontainer">

<div id="content" class="inside">
<h1><a id="ilogo" href="#">inviter</a></h1>
<div id="intro">
<h2>SMS & MMS Campaign Manager</h2>
<p class="tagline">
Run large scale SMS & MMS campaigns
</p>
<div class="signup-signin">
<a id="sign_up_btn" class="btn square" href='<%= new_user_registration_path %>'>
Join now.
</a>
<p>
Already a member?
<br>
<%= link_to "Sign In", new_user_session_url(:protocol => "https"), :class=>"btn square" %>
</p>
</div>
</div>
<div id="promoimg">
<img id="phone" src="assets/mobinv.jpg">
</div>

</div>
<div id="prop">
<ul class="primary">
<li id="organization">
<h2></h2>
</li>
<li id="analytics">
<h2></h2>
</li>
<li id="sharing">
<h2></h2>
</li>
</ul>
</div>

<div id="bottom">

</div>
</div>

</div>
<div id="footer">

<ul id="footer_links" class="homecontainer">
<li><a href="#">Help</a></li>
<li><a href="/a/contact_us">Contact</a></li>
<li><a href="<%= help_docs_path %>">Developers</a></li>
<li><a href="#">About</a></li>
<li><a href="#">Blog</a></li>
<li><a class="facebook" href="http://www.facebook.com/inviter">Facebook</a></li>
<li><a class="twitter" href="http://twitter.com/inviter">Twitter</a></li>
</ul>
<p class="copyright">© 2013 inviter™  ·  made in burlingame, ca</p>

</div>


</div>