config/routes.rb
require 'api_constraints'

Jupiter::Application.routes.draw do 

  resources :attachments

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1) do
        resources :shareables, path: '/shareable', only: [:create] 
        devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
        resources :messages, only: [:create, :index, :show] 
    end
    
    post '/mogreet/callback', to: 'callback#mogreet_callback', :defaults => { :format => 'xml' }
    post '/mogreet/response', to: 'callback#handle_mogreet_response'
    post '/twilio/callback', to: 'callback#twilio_callback'
    
    resources :recordings do
      collection do 
        get 'handle' => 'recordings#handle'
      end
      collection do 
        get 'complete' => 'recordings#complete'
      end
    end
  end
  
  scope '/a' do
    
    resources :help_docs
    
    resources :community_feeds, only: [:index] 

    resources :emails

    resources :messages
    
    resources :recordings

    resources :sms_archives

    resources :client_numbers

    resources :users_clients

    resources :recipients

    resources :sms_responses

    devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
    
    resources :shareables

    resources :clients

    resources :clicks do
      collection do 
        get '/' => 'clicks#create'
      end
    end
  
    post '/clicks/default/:id', to:  "clicks#default"
    
    get '/contact_us', to:  "home#contact_us"

    resources :email_templates
  
    resources :user_profiles
  end
  
  namespace :admin do |admin|
    resources :user_profiles
    resources :clients
    resources :messages
    resources :users
    resources :sms_responses
  end

  get '*short' => 'api/clicks#create', short: /\w{6}/

  root :to => "home#index"
  
  

end

app/controllers/admin/user_profiles_controller.rb
class Admin::UserProfilesController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /user_profiles
  # GET /user_profiles.json
  def index
    
    @links_grid = initialize_grid(User)
    authorize! :manage, User
    
    respond_to do |format|
      format.html 
      format.json { render json: @user }
    end
  end
  
  # GET /emails/1/edit
  def edit
    @user = User.find(params[:id])
    authorize! :manage, User
  end
  
  # PUT /recipients/1
  # PUT /recipients/1.json
  def update
    
    @user = User.find(params[:id])
    authorize! :manage, User

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to :controller=>'admin/user_profiles', :action => 'index' }
        format.json { head :no_content }
      else
        format.html 
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /recipients/1
  # DELETE /recipients/1.json
  def destroy
    @user = User.find(params[:id])
    authorize! :manage, User
    @user.destroy

    respond_to do |format|
      format.html { redirect_to :controller=>'admin/user_profiles', :action => 'index' }
      format.json { head :no_content }
    end
  end

end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
  
  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def index
    @user = User.find(current_user.id)

    respond_to do |format|
      format.html { render action: "show" }
      format.json { render json: @user }
    end
  end
  
  
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_filter :authenticate_user!
  skip_authorization_check
  # GET /user_profiles
  # GET /user_profiles.json
  def index
    
    @user = User.find(current_user.id) 

    respond_to do |format|
      format.html { render action: "show" }
      format.json { render json: @user }
    end
  end
  
  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
    @user = User.find(current_user.id)

    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end
  
  
end

app/helpers/admin/user_profiles_helper.rb
module Admin::UserProfilesHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/admin/user_profiles/_form.html.erb
<%= form_for([:admin,@user], :url => url_for(:controller => 'admin/user_profiles', :action => 'update')) do |f| %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>
  
  <div><%= f.label :role %><br />
  <%= f.collection_select :role, User::ROLES, :to_s, :humanize %></div>
  
  <div><%= f.label 'Application' %><br />
  <%= f.select( :client_id, Client.all.collect {|a| [a.title, a.id]} ) %></div>
   
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                clients_path, :class => 'btn' %>
  </div>
  

<% end %>

app/views/admin/user_profiles/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>Edit User</h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/user_profiles/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>Users</h1>
</div>
			
<%= grid(@links_grid, :show_filters => :yes)  do |g|

	g.column :name => 'Id', :attribute => 'id' do |user|
  	  user.id
	end
	g.column :name => 'Email', :attribute => 'email' do |user|
  	  user.email
	end
	g.column :name => 'Role', :attribute => 'role' do |user|
  	  user.role
	end
	g.column :name => 'Application', :attribute => 'client_id' do |user|
  	  user.client_id
	end
	g.column :name => 'Created At', :attribute => 'created_at' do |user|
  	  user.created_at
	end
	g.column :name => 'Updated At', :attribute => 'updated_at' do |user|
  	  user.updated_at
	end
	g.column do |user|
	    link_to('Edit', edit_admin_user_profile_path(user))
	end
	g.column do |user|
		link_to('Delete', admin_user_profile_path(user), :confirm => "Are you sure?", :method => :delete)
	end

end -%>

         